# Generated by Django 4.0.4 on 2022-05-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('room_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_film', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('surname', models.CharField(blank=True, max_length=250, null=True)),
                ('role', models.CharField(blank=True, choices=[('a', 'attore'), ('r', 'regista'), ('ar', 'attore/regista')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proiezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('number_spectators', models.IntegerField(blank=True, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.film')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_3d', models.BooleanField(blank=True, default=False, null=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cinema')),
                ('proiezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proiezione')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.ManyToManyField(related_name='cast', to='core.persona'),
        ),
    ]
