# Generated by Django 4.0.4 on 2022-05-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='room_number',
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nazionality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
