# Generated by Django 4.0.4 on 2022-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cinema_room_number_cinema_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='name',
            field=models.CharField(blank=True, choices=[('n', 'nord'), ('o', 'ovest'), ('e', 'est')], max_length=50, null=True),
        ),
    ]
