# Generated by Django 4.0.4 on 2022-05-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sala_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='name',
            field=models.CharField(blank=True, choices=[('nord', 'nord'), ('ovest', 'ovest'), ('est', 'est')], max_length=50, null=True),
        ),
    ]
