# Generated by Django 4.0.4 on 2022-07-17 16:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_post_status_post_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('post', django.db.models.manager.Manager()),
            ],
        ),
    ]
